AddCSLuaFile()

ENT.Base = "nz_zombie_walker_quartz_lab"
ENT.Type = "nextbot"
ENT.Category = "Brainz"
ENT.PrintName = "Zombie"
--ENT.PrintName = "Wheres me Mummy?"
ENT.Author = "GhostlyMoo"
ENT.Spawnable = true

ENT.Models = {
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_shirtless_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_1.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_2.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_3.mdl", Skin = 0, Bodygroups = {0,0}},
	{Model = "models/moo/_codz_ports/t10/zm/thetomb/moo_codz_t10_zmb_zombie_male_mummy_warrior_4.mdl", Skin = 0, Bodygroups = {0,0}},
}
