nzDialog:AddCustomDialog("blanchardExfil_Unavailable", "bo6/exfil/vox/blanchard/unavailable1.mp3", "Alpha team, exfil window closed.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Unavailable", "bo6/exfil/vox/blanchard/unavailable2.mp3", "Be advised, exfil window's closed.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Unavailable", "bo6/exfil/vox/blanchard/unavailable3.mp3", "Exfil bird headed to refuel. ", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Unavailable", "bo6/exfil/vox/blanchard/unavailable4.mp3", "Exfil bird re-tasked, will advise.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Unavailable", "bo6/exfil/vox/blanchard/unavailable5.mp3", "Exfil window missed, will advise when it re-opens.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Unavailable", "bo6/exfil/vox/blanchard/unavailable6.mp3", "Hey, need to shut down that pick up offer for now team.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Unavailable", "bo6/exfil/vox/blanchard/unavailable7.mp3", "Sorry Alpha, exfil helo's needed elsewhere.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Unavailable", "bo6/exfil/vox/blanchard/unavailable8.mp3", "Suspending exfil for now Alpha. You're on your own.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Unavailable", "bo6/exfil/vox/blanchard/unavailable9.mp3", "You snooze you lose. Exfil window closed.", "Blanchard", "bo6/exfil/blanchard.png")

nzDialog:AddCustomDialog("blanchardExfil_Available", "bo6/exfil/vox/blanchard/available2.mp3", "Chopper's available for exfil.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Available", "bo6/exfil/vox/blanchard/available3.mp3", "Exfil is available, Alpha team.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Available", "bo6/exfil/vox/blanchard/available4.mp3", "Exfil window is opening.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Available", "bo6/exfil/vox/blanchard/available5.mp3", "Extraction bird in your AO, limited time offer.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Available", "bo6/exfil/vox/blanchard/available6.mp3", "Extraction is ready when you are, Alpha.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Available", "bo6/exfil/vox/blanchard/available7.mp3", "Extraction's available in your AO.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Available", "bo6/exfil/vox/blanchard/available8.mp3", "Got a one-way ticket back to base with your name on it.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Available", "bo6/exfil/vox/blanchard/available9.mp3", "If you need to hit the exit button, we're ready.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Available", "bo6/exfil/vox/blanchard/available10.mp3", "If you need to tap out, exfil helo is ready to go.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Available", "bo6/exfil/vox/blanchard/available11.mp3", "Pick-up window's open.", "Blanchard", "bo6/exfil/blanchard.png")

nzDialog:AddCustomDialog("blanchardExfil_Start", "bo6/exfil/vox/blanchard/start1.mp3", "Chopper inbound for extraction, get to the LZ.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Start", "bo6/exfil/vox/blanchard/start2.mp3", "Pickup's inbound, hang tight.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Start", "bo6/exfil/vox/blanchard/start3.mp3", "Prepare for exfil, marking site.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Start", "bo6/exfil/vox/blanchard/start4.mp3", "Roger that. Bird headed your way.", "Blanchard", "bo6/exfil/blanchard.png")

nzDialog:AddCustomDialog("blanchardExfil_Arrive", "bo6/exfil/vox/pilot/chopper_arrived_1.mp3", "I'm in position, looks pretty hairy down there.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_Arrive", "bo6/exfil/vox/pilot/chopper_arrived_2.mp3", "Reporting for pick-up, X marks the spot.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_Arrive", "bo6/exfil/vox/pilot/chopper_arrived_3.mp3", "Extraction point in sight.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_Arrive", "bo6/exfil/vox/pilot/chopper_arrived_4.mp3", "On final approach to exfil location.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")

nzDialog:AddCustomDialog("blanchardExfil_Clear", "bo6/exfil/vox/pilot/clear_1.mp3", "Alpha Team, clear out the LZ or evac ain't happening.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_Clear", "bo6/exfil/vox/pilot/clear_2.mp3", "Too many bogeys on the ground — make some room!", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_Clear", "bo6/exfil/vox/pilot/clear_3.mp3", "LZ's crowded, get it under control!", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")

nzDialog:AddCustomDialog("blanchardExfil_30sec", "bo6/exfil/vox/blanchard/30sec1.mp3", "You got 30 seconds to catch that ride.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_30sec", "bo6/exfil/vox/blanchard/30sec2.mp3", "30 seconds, Alpha.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_30sec", "bo6/exfil/vox/blanchard/30sec3.mp3", "30 seconds on the clock, Alpha, move it!", "Blanchard", "bo6/exfil/blanchard.png")

nzDialog:AddCustomDialog("blanchardExfil_15sec", "bo6/exfil/vox/blanchard/15sec1.mp3", "15 seconds, get to the helo!", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_15sec", "bo6/exfil/vox/blanchard/15sec2.mp3", "Its now or never Alpha.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_15sec", "bo6/exfil/vox/blanchard/15sec3.mp3", "Last call, this bird won't wait.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_15sec", "bo6/exfil/vox/blanchard/15sec4.mp3", "Alpha! In or out?", "Blanchard", "bo6/exfil/blanchard.png")

nzDialog:AddCustomDialog("blanchardExfil_GetIn", "bo6/exfil/vox/pilot/get_in_1.mp3", "Greenlight for pick-up, all aboard.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_GetIn", "bo6/exfil/vox/pilot/get_in_2.mp3", "Nice work, we're go for exfil.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_GetIn", "bo6/exfil/vox/pilot/get_in_3.mp3", "Good lookin' LZ, get ready to board.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_GetIn", "bo6/exfil/vox/pilot/get_in_4.mp3", "Area clear n' proceeding with extraction.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")

nzDialog:AddCustomDialog("blanchardExfil_Success", "bo6/exfil/vox/blanchard/success1.mp3", "Copy that. Team, prep for debrief.", "Blanchard", "bo6/exfil/blanchard.png")
nzDialog:AddCustomDialog("blanchardExfil_Success", "bo6/exfil/vox/blanchard/success2.mp3", "Nice pull pilot.", "Blanchard", "bo6/exfil/blanchard.png")

nzDialog:AddCustomDialog("blanchardExfil_SuccessPilot", "bo6/exfil/vox/pilot/success_1.mp3", "Alpha is present and correct, RTB.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_SuccessPilot", "bo6/exfil/vox/pilot/success_2.mp3", "Brew some coffee we're comin' home.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_SuccessPilot", "bo6/exfil/vox/pilot/success_3.mp3", "All hands on board we're RTB.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_SuccessPilot", "bo6/exfil/vox/pilot/success_4.mp3", "Got a full house, we're outta' here.", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")

nzDialog:AddCustomDialog("blanchardExfil_Fail", "bo6/exfil/vox/pilot/fail_1.mp3", "What is that thing... Brace, Brace!", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_Fail", "bo6/exfil/vox/pilot/fail_2.mp3", "Mayday, Mayday, I'm goin' down!", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_Fail", "bo6/exfil/vox/pilot/fail_3.mp3", "It's got my skin, Mayday!", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")
nzDialog:AddCustomDialog("blanchardExfil_Fail", "bo6/exfil/vox/pilot/fail_4.mp3", "Shit, get it off!", "Exfil Pilot", "bo6/exfil/liberty_pilot.png")