nzDialog:AddCustomDialog("raptorExfil_Unavailable", "bo6/exfil/vox/raptor/unavailable1.mp3", "God damn it, tail rotor's stuck. Afraid i'm grounded for now.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Unavailable", "bo6/exfil/vox/raptor/unavailable2.mp3", "Gotta delay our Exfil. Too much wind shear.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Unavailable", "bo6/exfil/vox/raptor/unavailable3.mp3", "Raptor One, bringing the bad news. Got a fuel leak, repairing now.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Unavailable", "bo6/exfil/vox/raptor/unavailable4.mp3", "Raptor One, experiencing mechanical failure. Exfil not visible right now.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Unavailable", "bo6/exfil/vox/raptor/unavailable5.mp3", "Raptor One, going offline. I got to diagnose a mechanical issue.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Unavailable", "bo6/exfil/vox/raptor/unavailable6.mp3", "Sorry, extraction opportunity has expired. Headwinds too strong.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Unavailable", "bo6/exfil/vox/raptor/unavailable7.mp3", "Cancel the next exfil window. This bird's going to take a little more fixing.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Unavailable", "bo6/exfil/vox/raptor/unavailable8.mp3", "This rotor craft's got a malfunction. Evac canceled, till further notice.", "Raptor One", "bo6/exfil/pilot.png")

nzDialog:AddCustomDialog("raptorExfil_Available", "bo6/exfil/vox/raptor/available1.mp3", "Got the old bird up and running for now. Evac available.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Available", "bo6/exfil/vox/raptor/available2.mp3", "I know y'all have your hands full, but I'm ready to get us out of here whenever you are.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Available", "bo6/exfil/vox/raptor/available3.mp3", "If y'all want to pull the ripcord, just say the word.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Available", "bo6/exfil/vox/raptor/available4.mp3", "Your asses need to ride out of here. I got the chopper ready.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Available", "bo6/exfil/vox/raptor/available5.mp3", "Raptor One, ready to extract, whatever you want to bug out.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Available", "bo6/exfil/vox/raptor/available6.mp3", "Raptor One, sky tours is open for business. Seriously. We can evac if you need to.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Available", "bo6/exfil/vox/raptor/available7.mp3", "This is Raptor One, give me a holler, if you need to exfil.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Available", "bo6/exfil/vox/raptor/available8.mp3", "This is Raptor One, hope you're all hanging in there but, i'm ready to go, whenever you are.", "Raptor One", "bo6/exfil/pilot.png")

nzDialog:AddCustomDialog("raptorExfil_Start", "bo6/exfil/vox/raptor/start1.mp3", "Hear you loud and clear. Commencement retrieval op.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Start", "bo6/exfil/vox/raptor/start2.mp3", "Acknowledged. On my way!", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Start", "bo6/exfil/vox/raptor/start3.mp3", "Copy that, Raptor One headed to exfil point.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Start", "bo6/exfil/vox/raptor/start4.mp3", "Extraction request received.", "Raptor One", "bo6/exfil/pilot.png")

nzDialog:AddCustomDialog("raptorExfil_Arrive", "bo6/exfil/vox/raptor/arrive1.mp3", "I'm at the LZ. Time to punch out.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Arrive", "bo6/exfil/vox/raptor/arrive2.mp3", "I'm in position. Your chariot awaits.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Arrive", "bo6/exfil/vox/raptor/arrive3.mp3", "Raptor One, at the evac point.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Arrive", "bo6/exfil/vox/raptor/arrive4.mp3", "Raptor One, in position for exfil.", "Raptor One", "bo6/exfil/pilot.png")

nzDialog:AddCustomDialog("raptorExfil_Clear", "bo6/exfil/vox/raptor/clear1.mp3", "LZ is overrun with enemies. Make a hole down there.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Clear", "bo6/exfil/vox/raptor/clear2.mp3", "Area's too hot to proceed. How about some crowd control?", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Clear", "bo6/exfil/vox/raptor/clear3.mp3", "Can't proceed with evac, till you clear them out.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Clear", "bo6/exfil/vox/raptor/clear4.mp3", "Exfil side needs some house cleaning.", "Raptor One", "bo6/exfil/pilot.png")

nzDialog:AddCustomDialog("raptorExfil_30sec", "bo6/exfil/vox/raptor/30sec1.mp3", "Looking at 30 seconds.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_30sec", "bo6/exfil/vox/raptor/30sec2.mp3", "30 seconds. You need to move, before we're toast.", "Raptor One", "bo6/exfil/pilot.png")

nzDialog:AddCustomDialog("raptorExfil_15sec", "bo6/exfil/vox/raptor/15sec1.mp3", "Time's up, in or out!", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_15sec", "bo6/exfil/vox/raptor/15sec2.mp3", "You only got seconds to spare. It's do or die time.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_15sec", "bo6/exfil/vox/raptor/15sec3.mp3", "Damn! We got maybe 15 seconds.", "Raptor One", "bo6/exfil/pilot.png")

nzDialog:AddCustomDialog("raptorExfil_GetIn", "bo6/exfil/vox/raptor/getin1.mp3", "Raptor One, now boarding all passengers.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_GetIn", "bo6/exfil/vox/raptor/getin2.mp3", "Raptor One, ready for board.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_GetIn", "bo6/exfil/vox/raptor/getin3.mp3", "Take a seat. I don't plan on hanging around.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_GetIn", "bo6/exfil/vox/raptor/getin4.mp3", "Down to the wire here, folks.", "Raptor One", "bo6/exfil/pilot.png")

nzDialog:AddCustomDialog("raptorExfil_Success", "bo6/exfil/vox/raptor/success1.mp3", "Raptor One, all personnel secure. We're getting off this damn rock.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Success", "bo6/exfil/vox/raptor/success2.mp3", "Raptor One, got a full house on board.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Success", "bo6/exfil/vox/raptor/success3.mp3", "Team strapped in. Proceeding with extraction, too. Well, not here.", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Success", "bo6/exfil/vox/raptor/success4.mp3", "We're clear. Let's go!", "Raptor One", "bo6/exfil/pilot.png")

nzDialog:AddCustomDialog("raptorExfil_Fail", "bo6/exfil/vox/raptor/fail1.mp3", "Mayday, Mayday! Raptor One, going down!", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Fail", "bo6/exfil/vox/raptor/fail2.mp3", "Not good, prep for impact!", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Fail", "bo6/exfil/vox/raptor/fail3.mp3", "Raptor One, we are f.u.b.a.r!", "Raptor One", "bo6/exfil/pilot.png")
nzDialog:AddCustomDialog("raptorExfil_Fail", "bo6/exfil/vox/raptor/fail4.mp3", "Shit! Brace, Brace!", "Raptor One", "bo6/exfil/pilot.png")