nzDialog:AddCustomDialog("BaseKillstreak_AirEnd", "bo6/ks/base1.mp3", "Copy that, Phantom, thanks for the work.", "TAACOM")
nzDialog:AddCustomDialog("BaseKillstreak_AirEnd", "bo6/ks/base2.mp3", "Thanks for the work, Cloaker, RTB.", "TAACOM")
nzDialog:AddCustomDialog("BaseKillstreak_AirEnd", "bo6/ks/base3.mp3", "Copy, Danger 3-5, thanks much.", "TAACOM")

nzDialog:AddCustomDialog("ChopperKillstreak_Start", "bo6/ks/chopper_start1.mp3", "Targets in range, air to ground away.", "Chopper Crew")
nzDialog:AddCustomDialog("ChopperKillstreak_End", "bo6/ks/chopper_end1.mp3", "Bingo fuel, heading back to base.", "Chopper Crew")
nzDialog:AddCustomDialog("ChopperKillstreak_Fuel", "bo6/ks/chopper_fuel1.mp3", "Fuel's getting low, take your shot!", "Chopper Crew")
nzDialog:AddCustomDialog("ChopperKillstreak_Fuel", "bo6/ks/chopper_fuel2.mp3", "MTC 50% expanded.", "Chopper Crew")
nzDialog:AddCustomDialog("ChopperKillstreak_Fuel", "bo6/ks/chopper_fuel3.mp3", "Mission timeline 50% expanded.", "Chopper Crew")
nzDialog:AddCustomDialog("ChopperKillstreak_Fuel", "bo6/ks/chopper_fuel4.mp3", "MTC 50% expanded.", "Chopper Crew")
nzDialog:AddCustomDialog("ChopperKillstreak_Kill", "bo6/ks/chopper_kill1.mp3", "Confirming multiple bogeys down!", "Chopper Crew")
nzDialog:AddCustomDialog("ChopperKillstreak_Kill", "bo6/ks/chopper_kill2.mp3", "Shot's good, multiple down!", "Chopper Crew")
nzDialog:AddCustomDialog("ChopperKillstreak_Kill", "bo6/ks/chopper_kill3.mp3", "MKIA, watching for rescue, teams.!", "Chopper Crew")
nzDialog:AddCustomDialog("ChopperKillstreak_Kill", "bo6/ks/chopper_kill4.mp3", "MKIA, good shoot, good shoot.", "Chopper Crew")
nzDialog:AddCustomDialog("ChopperKillstreak_Kill", "bo6/ks/chopper_kill5.mp3", "MKIA, nice strike!", "Chopper Crew")
nzDialog:AddCustomDialog("ChopperKillstreak_Kill", "bo6/ks/chopper_kill6.mp3", "Multiple hostiles down, continuing on mission.", "Chopper Crew")