nzDialog:AddCustomDialog("tombExfil_Unavailable", "bo6/exfil/vox/tomb/unavailable_1.mp3", "We no longer have evac' capability. Raptor One out.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Unavailable", "bo6/exfil/vox/tomb/unavailable_2.mp3", "This is Raptor One, opprotunity for exfil has expired.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Unavailable", "bo6/exfil/vox/tomb/unavailable_3.mp3", "I'm afraid we are unable to collect you from the digsite at this time.", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_Unavailable", "bo6/exfil/vox/tomb/unavailable_4.mp3", "Avalon air control is patrolling our airspace. Window is closed for evac.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Unavailable", "bo6/exfil/vox/tomb/unavailable_5.mp3", "We're currently no-go on exfil. Strauss really, really has to take a leak.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Unavailable", "bo6/exfil/vox/tomb/unavailable_6.mp3", "I'm grounded til' wind conditions improve. Gonna' play cards with Strauss. This fucker's really good!", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Unavailable", "bo6/exfil/vox/tomb/unavailable_7.mp3", "Raptor One at bingo! We are RTB. Stay alive down there while we top off.", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_Unavailable", "bo6/exfil/vox/tomb/unavailable_8.mp3", "Raptor One did not appreciate my adjusment to his instrumentation. We are grounded for now.", "Strauss", "bo6/exfil/tomb_strauss.png")

nzDialog:AddCustomDialog("tombExfil_Available", "bo6/exfil/vox/tomb/available_1.mp3", "Chopper is good to go when you're done spelunkin' down there.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Available", "bo6/exfil/vox/tomb/available_2.mp3", "Heads up folks, exfil is available. Raptor One out.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Available", "bo6/exfil/vox/tomb/available_3.mp3", "This is Raptor One, if you can hear me down there evac is ready.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Available", "bo6/exfil/vox/tomb/available_4.mp3", "This is Raptor One, pick up is available. Don't leave me here with Strauss all day!", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Available", "bo6/exfil/vox/tomb/available_5.mp3", "If you've had your fill of suffering and scoundrels, the chopper is ready to recieve you.", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_Available", "bo6/exfil/vox/tomb/available_6.mp3", "Just holler if you wanna get pulled out. Seriously. I'll trade anyone for Strauss.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Available", "bo6/exfil/vox/tomb/available_7.mp3", "Raptor One informs me that we can now extricate you from that cursed hole underground.", "Strauss", "bo6/exfil/tomb_strauss.png")

nzDialog:AddCustomDialog("tombExfil_Start", "bo6/exfil/vox/tomb/incoming_1.mp3", "Don't gotta' tell me twice. See you soon!", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Start", "bo6/exfil/vox/tomb/incoming_2.mp3", "Acknowledged. Me and mothballrat are on the move.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Start", "bo6/exfil/vox/tomb/incoming_3.mp3", "Copy that, on my way to the rendezvous point. Raptor One out.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Start", "bo6/exfil/vox/tomb/incoming_4.mp3", "We have recieved your request and will consider it. I was merely joking — we are coming.", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_Start", "bo6/exfil/vox/tomb/incoming_5.mp3", "Finally! I have taken enough of Raptor Ones money playing poker.", "Strauss", "bo6/exfil/tomb_strauss.png")

nzDialog:AddCustomDialog("tombExfil_Arrive", "bo6/exfil/vox/tomb/arrived_1.mp3", "Get your asshats upstairs I'm at the extraction point.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Arrive", "bo6/exfil/vox/tomb/arrived_2.mp3", "Raptor One, I'm at the LZ lets get the hell outta' here!", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Arrive", "bo6/exfil/vox/tomb/arrived_3.mp3", "Hoverin' over the X. Gimme a minute — this site is tricky.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Arrive", "bo6/exfil/vox/tomb/arrived_4.mp3", "We are in your vicinity, I recommend moving above ground.", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_Arrive", "bo6/exfil/vox/tomb/arrived_5.mp3", "We have arrived. Raptor One insists we will fit in this hole. I am not convinced.", "Strauss", "bo6/exfil/tomb_strauss.png")

nzDialog:AddCustomDialog("tombExfil_Clear", "bo6/exfil/vox/tomb/clear_1.mp3", "No shot I'm landing in that shit show — clear them out!", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Clear", "bo6/exfil/vox/tomb/clear_2.mp3", "Raptor One has eyes on the LZ. Don't stop slaying those shuppers yet. ", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Clear", "bo6/exfil/vox/tomb/clear_3.mp3", "If we land now we will not survive. You still have bullets, yes?", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_Clear", "bo6/exfil/vox/tomb/clear_4.mp3", "Raptor One is waving excitedly and whats me to say... oh dear — get my motherfucking LZ clear, motherfuckers.", "Strauss", "bo6/exfil/tomb_strauss.png")

nzDialog:AddCustomDialog("tombExfil_30sec", "bo6/exfil/vox/tomb/30_seconds_left_1.mp3", "In half a minute we are leaving — preferably with you aboard!", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_30sec", "bo6/exfil/vox/tomb/30_seconds_left_2.mp3", "Time is expiring — try not to do the same!", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_30sec", "bo6/exfil/vox/tomb/30_seconds_left_3.mp3", "Less than a minute, move your asses!", "Raptor One", "bo6/exfil/tomb_pilot.png")

nzDialog:AddCustomDialog("tombExfil_15sec", "bo6/exfil/vox/tomb/15_seconds_left_1.mp3", "Punctuality is a virtue, 'specially now!", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_15sec", "bo6/exfil/vox/tomb/15_seconds_left_2.mp3", "I would prefer not to become yet another relic in this place.", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_15sec", "bo6/exfil/vox/tomb/15_seconds_left_3.mp3", "15 seconds, and then me and Mr. Whiskers are out of here!", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_15sec", "bo6/exfil/vox/tomb/15_seconds_left_4.mp3", "Last call, I'm not fuckin' around!", "Raptor One", "bo6/exfil/tomb_pilot.png")

nzDialog:AddCustomDialog("tombExfil_GetIn", "bo6/exfil/vox/tomb/landing_1.mp3", "Hold on Strauss! You can take drink orders once they're on board.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_GetIn", "bo6/exfil/vox/tomb/landing_2.mp3", "Landing underway! The terrain is gonna' make for a lotta' downwash.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_GetIn", "bo6/exfil/vox/tomb/landing_3.mp3", "Anyone want a snack? I have slightly stale raisins.", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_GetIn", "bo6/exfil/vox/tomb/landing_4.mp3", "Prepare to board. Bite your shoes. None of you were born in a barn after all.", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_GetIn", "bo6/exfil/vox/tomb/landing_5.mp3", "Coming down, never fear I am prepared this time. I have a sick bag.", "Strauss", "bo6/exfil/tomb_strauss.png")

nzDialog:AddCustomDialog("tombExfil_Success", "bo6/exfil/vox/tomb/success_1.mp3", "Our AC is optimal, we are outta' here.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Success", "bo6/exfil/vox/tomb/success_2.mp3", "You guys look great for willingly goin' into a big spooky hole.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Success", "bo6/exfil/vox/tomb/success_3.mp3", "Hehe, see? Easy. Venturing home.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Success", "bo6/exfil/vox/tomb/success_4.mp3", "Exfil is successful once again! Just sayin'.", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Success", "bo6/exfil/vox/tomb/success_5.mp3", "No presents for me? Not even a... skull or a... damn rock?", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Success", "bo6/exfil/vox/tomb/success_6.mp3", "All passengers accounted for. Does everyone have all their fingers and toes?", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_Success", "bo6/exfil/vox/tomb/success_7.mp3", "Ugh... my cardiologist will not be pleased, next time I see her.", "Strauss", "bo6/exfil/tomb_strauss.png")

nzDialog:AddCustomDialog("tombExfil_Fail", "bo6/exfil/vox/tomb/fail_1.mp3", "Noo! I have yet to write my will!", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_Fail", "bo6/exfil/vox/tomb/fail_2.mp3", "Where'd that thing come from! Goin' in hard!", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Fail", "bo6/exfil/vox/tomb/fail_3.mp3", "NEIN! I'm too young to die!", "Strauss", "bo6/exfil/tomb_strauss.png")
nzDialog:AddCustomDialog("tombExfil_Fail", "bo6/exfil/vox/tomb/fail_4.mp3", "Shit, we're going down!", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Fail", "bo6/exfil/vox/tomb/fail_5.mp3", "Mayday, May-fuckin'-day!", "Raptor One", "bo6/exfil/tomb_pilot.png")
nzDialog:AddCustomDialog("tombExfil_Fail", "bo6/exfil/vox/tomb/fail_6.mp3", "Damn things got my skin!", "Raptor One", "bo6/exfil/tomb_pilot.png")