nzDialog:AddCustomDialog("citadelleExfil_Unavailable", "bo6/exfil/vox/citadelle/unavailable_1.mp3", "I'm afraid weather conditions are not condusive for exfil — ehm... Strauss out!", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Unavailable", "bo6/exfil/vox/citadelle/unavailable_2.mp3", "Who the fuck gave the old man an egg salad sandwich? Exfil's closed while I air this bird out!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Unavailable", "bo6/exfil/vox/citadelle/unavailable_3.mp3", "Alas, there are technical issues with the helo and Raptor One forbids me from playing grease monkey.", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Unavailable", "bo6/exfil/vox/citadelle/unavailable_4.mp3", "Fuck! Rotations a bit janky, I'm pulling back til' I figure this out.", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Unavailable", "bo6/exfil/vox/citadelle/unavailable_5.mp3", "Currently closed for business, hope there ain't no dragon guard in that place!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Unavailable", "bo6/exfil/vox/citadelle/unavailable_6.mp3", "Winds not being cooperative, I'll let you know when it dies down.", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Unavailable", "bo6/exfil/vox/citadelle/unavailable_7.mp3", "I'm pullin' back for the moment. Performin' safety check.", "Raptor One", "bo6/exfil/citadelle_pilot.png")

nzDialog:AddCustomDialog("citadelleExfil_Available", "bo6/exfil/vox/citadelle/available_1.mp3", "Ahem, Strauss One here — your aerial chariot awaits.", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Available", "bo6/exfil/vox/citadelle/available_2.mp3", "Straus to Citadelle, we are standing buy should you choose to evacuate!", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Available", "bo6/exfil/vox/citadelle/available_3.mp3", "You have the option to make an exit, if you've had enough of avalon.", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Available", "bo6/exfil/vox/citadelle/available_4.mp3", "This is Raptor One front meter's full. Holler when you need me.", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Available", "bo6/exfil/vox/citadelle/available_5.mp3", "Good to go for castle extraction if yall need to tap out.", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Available", "bo6/exfil/vox/citadelle/available_6.mp3", "Exfil's ready if you're sick of that shit-tastic ren fair.", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Available", "bo6/exfil/vox/citadelle/available_7.mp3", "Raptor One here, got a full tank, who needs a ride?", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Available", "bo6/exfil/vox/citadelle/available_8.mp3", "Had enough spooky castle shit for one day?", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Available", "bo6/exfil/vox/citadelle/available_9.mp3", "Just me and the old coot up here. Wouldn't mind some company. Seriously.", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Available", "bo6/exfil/vox/citadelle/available_10.mp3", "Its okay, if you wanna tell me, how much you missed my pretty face.", "Raptor One", "bo6/exfil/citadelle_pilot.png")

nzDialog:AddCustomDialog("citadelleExfil_Start", "bo6/exfil/vox/citadelle/chopper_incoming_1.mp3", "Your request must be submitted in triplicate — Kidding, we are on our way.", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Start", "bo6/exfil/vox/citadelle/chopper_incoming_2.mp3", "Your knights in shining 'chopper' shall arrive shortly.", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Start", "bo6/exfil/vox/citadelle/chopper_incoming_3.mp3", "On my way with ol' schnitzel for brains.", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Start", "bo6/exfil/vox/citadelle/chopper_incoming_4.mp3", "Heard that, get your butts to the exfil point!", "Raptor One", "bo6/exfil/citadelle_pilot.png")

nzDialog:AddCustomDialog("citadelleExfil_Arrive", "bo6/exfil/vox/citadelle/chopper_arrived_1.mp3", "Er, Strauss here. We are in position, just look for the whirly bird. That would be us.", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Arrive", "bo6/exfil/vox/citadelle/chopper_arrived_2.mp3", "We are at exfil! Regretably, the architects did not foresee the need for a helipad.", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Arrive", "bo6/exfil/vox/citadelle/chopper_arrived_3.mp3", "In position in extraction point — not a lot of options in this castle.", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Arrive", "bo6/exfil/vox/citadelle/chopper_arrived_4.mp3", "Get where I can see ya' — Castle extract is a bitch!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Arrive", "bo6/exfil/vox/citadelle/chopper_arrived_5.mp3", "'Scuse me while I make my grand entrance!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Arrive", "bo6/exfil/vox/citadelle/chopper_arrived_6.mp3", "Arrived at rendezvous point.", "Raptor One", "bo6/exfil/citadelle_pilot.png")

nzDialog:AddCustomDialog("citadelleExfil_Clear", "bo6/exfil/vox/citadelle/clear_1.mp3", "Clear the deck my friends, we cannot descend into a riot!", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Clear", "bo6/exfil/vox/citadelle/clear_2.mp3", "Get those fuckers off my LZ!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Clear", "bo6/exfil/vox/citadelle/clear_3.mp3", "Can't land on a moving meat pie!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Clear", "bo6/exfil/vox/citadelle/clear_4.mp3", "Too much foot traffic down there!", "Raptor One", "bo6/exfil/citadelle_pilot.png")

nzDialog:AddCustomDialog("citadelleExfil_30sec", "bo6/exfil/vox/citadelle/30_seconds_left_1.mp3", "In half a minute we are leaving — preferably with you aboard!", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_30sec", "bo6/exfil/vox/citadelle/30_seconds_left_2.mp3", "30 seconds and this castle tour is over!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_30sec", "bo6/exfil/vox/citadelle/30_seconds_left_3.mp3", "Less than a minute, move your asses!", "Raptor One", "bo6/exfil/citadelle_pilot.png")

nzDialog:AddCustomDialog("citadelleExfil_15sec", "bo6/exfil/vox/citadelle/15_seconds_left_1.mp3", "Punctuality is a virtue, 'specially now!", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_15sec", "bo6/exfil/vox/citadelle/15_seconds_left_2.mp3", "I would prefer not to become yet another relic in this place.", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_15sec", "bo6/exfil/vox/citadelle/15_seconds_left_3.mp3", "15 seconds, and then me and Mr. Whiskers are out of here!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_15sec", "bo6/exfil/vox/citadelle/15_seconds_left_4.mp3", "Last call, I'm not fuckin' around!", "Raptor One", "bo6/exfil/citadelle_pilot.png")

nzDialog:AddCustomDialog("citadelleExfil_GetIn", "bo6/exfil/vox/citadelle/get_in_1.mp3", "Get in! The parking fees here murder!", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_GetIn", "bo6/exfil/vox/citadelle/get_in_2.mp3", "Get in, quickly! We can ill affort loiter here.", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_GetIn", "bo6/exfil/vox/citadelle/get_in_3.mp3", "Shake a leg, I only want living people on this bird!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_GetIn", "bo6/exfil/vox/citadelle/get_in_4.mp3", "All aboard the Fuck This Shit Express!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_GetIn", "bo6/exfil/vox/citadelle/get_in_5.mp3", "We're down to the wire, hustle!", "Raptor One", "bo6/exfil/citadelle_pilot.png")

nzDialog:AddCustomDialog("citadelleExfil_Success", "bo6/exfil/vox/citadelle/exfil_success_1.mp3", "You smell like a slaughter house, but at least you are alive.", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Success", "bo6/exfil/vox/citadelle/exfil_success_2.mp3", "It is safe to say you have worn out your welcome in the citadelle!", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Success", "bo6/exfil/vox/citadelle/exfil_success_3.mp3", "That castle is trashed. Gonna suck to clean that up.", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Success", "bo6/exfil/vox/citadelle/exfil_success_4.mp3", "Success! Get us out of here Raptor One!", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Success", "bo6/exfil/vox/citadelle/exfil_success_5.mp3", "Would anyone be mad if I landed at the nearest steakhouse?", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Success", "bo6/exfil/vox/citadelle/exfil_success_6.mp3", "Everyone's accounted for, mission success!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Success", "bo6/exfil/vox/citadelle/exfil_success_7.mp3", "Got a full basket, headed out!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Success", "bo6/exfil/vox/citadelle/exfil_success_8.mp3", "You have fun stormin' the castle?", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Success", "bo6/exfil/vox/citadelle/exfil_success_9.mp3", "Cleared for takeoff!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Success", "bo6/exfil/vox/citadelle/exfil_success_10.mp3", "Pick up complete!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Success", "bo6/exfil/vox/citadelle/exfil_success_11.mp3", "Sadly, there is no incantation for air sickness.", "Strauss", "bo6/exfil/strauss.png")

nzDialog:AddCustomDialog("citadelleExfil_Fail", "bo6/exfil/vox/citadelle/exfil_fail_1.mp3", "Auf wiedersehen, cruel world.", "Strauss", "bo6/exfil/strauss.png")
nzDialog:AddCustomDialog("citadelleExfil_Fail", "bo6/exfil/vox/citadelle/exfil_fail_2.mp3", "Shit, we're going down!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Fail", "bo6/exfil/vox/citadelle/exfil_fail_3.mp3", "Mayday, May-fuckin'-day!", "Raptor One", "bo6/exfil/citadelle_pilot.png")
nzDialog:AddCustomDialog("citadelleExfil_Fail", "bo6/exfil/vox/citadelle/exfil_fail_4.mp3", "Damn things got my skin!", "Raptor One", "bo6/exfil/citadelle_pilot.png")