game.AddParticles("particles/zoderG.pcf")
game.AddParticles("particles/puker_attacker.pcf")
game.AddParticles("particles/bruteattackds2.pcf")
game.AddParticles("particles/ubr.pcf")

local particlename = {
	"warth_smoke",
	"ubr_heal",
"ubr_heal2",
"warth_attack2",
"warth_body2",
"roarer_huller",
"roarer_huller2",
"puker_rangeattack",
"puker_rangeattack2",
"puker_rangeattack3",
"puker_rangeattack4",
"puker_rangeball",
"spitter_rangeattack",
"spitter_rangeball",
"brute_rangeattack",
"brute_rangeball",
"brute_jumped",
"exploder_boom",
"exploder_boom2",
"exploder_boom3",
"exploder_boom4",
"exploder_boom5",
"kong_dead",
"kong_dead2",
"kong_dead3",
"kong_dead4",
"baby_dead",
"baby_dead2",
"baby_dead3",
"tencle_attack2",
"tencle_attacker",
"divider_slash",
"divider_slash2",
"divider_slash3",
"lurker_range",
"corpose change",
"corpose change2",
"corpose finish",
"puker_ballboom",
"puker_rangeattack5",
"puker_rangeattack6",
"puker_rangeattack7",
"puker_rangeball2",
"limb_crash",
"pregent_belley",
"pregent_belley2",
}
for _,v in ipairs(particlename) do PrecacheParticleSystem(v) end
