
-- Moo Particles(I puked particles all over the place)
game.AddParticles("particles/moo_misc_fx.pcf")
game.AddParticles("particles/loonicity_particles.pcf")
game.AddParticles("particles/temp_fx.pcf")
game.AddParticles("particles/tomb_pap_red.pcf")

PrecacheParticleSystem("zmb_zombie_spawn_dirt")
PrecacheParticleSystem("zmb_zombie_spawn_snow")

PrecacheParticleSystem("zmb_mutated_electric_aura")
PrecacheParticleSystem("zmb_mutated_electric_attack")
PrecacheParticleSystem("zmb_mutated_electric_attack_tell")
PrecacheParticleSystem("zmb_mutated_electric_step")
PrecacheParticleSystem("zmb_mutated_water_aura")
PrecacheParticleSystem("zmb_mutated_water_step")
PrecacheParticleSystem("zmb_mutated_plasma_aura")
PrecacheParticleSystem("zmb_mutated_plasma_step")

PrecacheParticleSystem("zmb_toxicpuddle")
PrecacheParticleSystem("zmb_toxicpuddle_small")

PrecacheParticleSystem("zmb_firepit")
PrecacheParticleSystem("zmb_dog_spawn_fireball")

PrecacheParticleSystem("zmb_abom_beam")

PrecacheParticleSystem("zmb_smoker_aura")
PrecacheParticleSystem("zmb_smoker_cloud")

PrecacheParticleSystem("zmb_disciple_aura")
PrecacheParticleSystem("zmb_disciple_blast")
PrecacheParticleSystem("zmb_disciple_hand_blast")
PrecacheParticleSystem("zmb_disciple_lifedrain")

PrecacheParticleSystem("zmb_quad_teleport")
PrecacheParticleSystem("zmb_gas_trail")
PrecacheParticleSystem("zmb_gas_explo")

PrecacheParticleSystem("zmb_trickster_aura")
PrecacheParticleSystem("zmb_trickster_portal")
PrecacheParticleSystem("zmb_trickster_charge_tell")
PrecacheParticleSystem("zmb_trickster_mine")
PrecacheParticleSystem("zmb_trickster_mine_blast")

PrecacheParticleSystem("zmb_mimic_mouth")
PrecacheParticleSystem("zmb_mimic_trans")
PrecacheParticleSystem("zmb_mimic_hide")
PrecacheParticleSystem("zmb_shock_mimic_aura")

PrecacheParticleSystem("zmb_explosive_zombie_aura")
PrecacheParticleSystem("zmb_explosive_zombie_step")
PrecacheParticleSystem("zmb_explosive_zombie_explo")

PrecacheParticleSystem("zmb_screamer_shoulder")

PrecacheParticleSystem("zmb_monster_explosion")

PrecacheParticleSystem("tomb_pap_eye")
PrecacheParticleSystem("tomb_pap_roller")
PrecacheParticleSystem("tomb_pap_roller_lens_flare")
PrecacheParticleSystem("tomb_pap_eye_red")
PrecacheParticleSystem("tomb_pap_roller_red")
PrecacheParticleSystem("tomb_pap_roller_lens_flare_red")

PrecacheParticleSystem("mob_box_aura")

PrecacheParticleSystem("zmb_margwa_spawn")
PrecacheParticleSystem("zmb_margwa_spawn_fire")
PrecacheParticleSystem("zmb_margwa_spawn_shadow")
PrecacheParticleSystem("zmb_fire_margwa_firetell")
PrecacheParticleSystem("zmb_fire_margwa_firewave")
PrecacheParticleSystem("zmb_shadow_margwa_shadowtell")
PrecacheParticleSystem("zmb_shadow_margwa_shockwave_explo")
PrecacheParticleSystem("zmb_shadow_margwa_shadowportal")
PrecacheParticleSystem("zmb_shadow_margwa_chomper_explo")
PrecacheParticleSystem("zmb_zombie_shadow_marked")
PrecacheParticleSystem("zmb_zombie_shadow_trap")
PrecacheParticleSystem("fire_margwa_footstep")
PrecacheParticleSystem("shdw_margwa_footstep")
PrecacheParticleSystem("shdw_margwa_smoke")

PrecacheParticleSystem("zmb_cyborg_dismember_limb")
PrecacheParticleSystem("zmb_cybord_impact_headshot")
PrecacheParticleSystem("zmb_cyborg_hound_explosion")

PrecacheParticleSystem("zmb_amal_death")
PrecacheParticleSystem("zmb_amal_death_drops")
PrecacheParticleSystem("zmb_amal_death_model")

PrecacheParticleSystem("zmb_ghoul_ranged_attack")

-- SNPC Particles
game.AddParticles("particles/horror/bloodsplosion.pcf")
game.AddParticles("particles/alien_swarm/mnb_flamethrower.pcf")
game.AddParticles("particles/starship_troopers/sst_acidbug_fx.pcf")
game.AddParticles("particles/halo/main_effects.pcf")
game.AddParticles("particles/doom/doom_fx.pcf")
game.AddParticles("particles/half-life_alyx/hla_antlion_blue_fx.pcf")
game.AddParticles("particles/half-life_alyx/hla_antlion_orange_fx.pcf")
game.AddParticles("particles/npcarmor.pcf")

PrecacheParticleSystem("spit_impact_blue")
PrecacheParticleSystem("spit_impact_orange")
PrecacheParticleSystem("spit_impact_yellow") -- Was blue, but recolored it yellow.
PrecacheParticleSystem("spit_trail_blue")
PrecacheParticleSystem("spit_trail_orange")
PrecacheParticleSystem("spit_trail_glow_yellow")
PrecacheParticleSystem("asw_mnb_flamethrower")
PrecacheParticleSystem("acidbug_spit_trail")
PrecacheParticleSystem("acidbug_spit_impact")
PrecacheParticleSystem("horror_bloodgibs")
PrecacheParticleSystem("horror_bloodsplosion")
PrecacheParticleSystem("horror_bloodsplosion_gib")
PrecacheParticleSystem("hcea_hunter_ab_charge")
PrecacheParticleSystem("hcea_hunter_ab_muzzle")
PrecacheParticleSystem("doom_wraith_teleport")
PrecacheParticleSystem("doom_hellunit_aura")
PrecacheParticleSystem("doom_caco_blast")
PrecacheParticleSystem("doom_mancu_blast")
PrecacheParticleSystem("ins_blood_impact_generic")
PrecacheParticleSystem("npcarmor_hit")
PrecacheParticleSystem("npcarmor_break")

-- Misc/Other Particles
game.AddParticles("particles/drops_powerups_new.pcf")
PrecacheParticleSystem("nz_powerup_classic_intro")
PrecacheParticleSystem("nz_powerup_classic_loop")
PrecacheParticleSystem("nz_powerup_poof")

game.AddParticles("particles/driese_fx.pcf")
game.AddParticles("particles/brutus_burning_footstep.pcf")
game.AddParticles("particles/vman_explosion.pcf")

PrecacheParticleSystem("driese_tp_arrival_ambient")
PrecacheParticleSystem("driese_tp_arrival_ambient_lightning")
PrecacheParticleSystem("driese_tp_arrival_ambient_xy")
PrecacheParticleSystem("driese_tp_arrival_phase1")
PrecacheParticleSystem("driese_tp_arrival_phase2")
PrecacheParticleSystem("driese_tp_arrival_impact_fx02_a")
PrecacheParticleSystem("driese_tp_arrival_lightning_static_1")
PrecacheParticleSystem("driese_tp_departure_phase1")
PrecacheParticleSystem("driese_tp_departure_phase2")
PrecacheParticleSystem("lightning_hit_swave_xy")
PrecacheParticleSystem("lightning_hit_swave_xz")
PrecacheParticleSystem("brutus_burning_footstep")
PrecacheParticleSystem("dusty_explosion_rockets")
PrecacheParticleSystem("doom_de_cybermancubus_fireball_glow")
