//BLACK OPS 4 WONDER WEAPONS

tfa.keybind.bo4ww.dg5.attack=震荡
tfa.keybind.bo4ww.dg5.attack2=加电
tfa.keybind.bo4ww.dg5.altattack=放置

tfa.keybind.bo4ww.hellfire.attack=喷射火焰
tfa.keybind.bo4ww.hellfire.attack2=气体冲击
tfa.keybind.bo4ww.hellfire.altattack=地狱风暴

tfa.keybind.bo4ww.overkill.attack=开火
tfa.keybind.bo4ww.overkill.attack2=发射榴弹
tfa.keybind.bo4ww.overkill.altattack=自毁

tfa.keybind.bo4ww.katana.attack=劈砍
tfa.keybind.bo4ww.katana.attack2=残暴突刺
tfa.keybind.bo4ww.katana.altattack=死亡暗影

tfa.ammo.bo4ww.winters=寒冰细胞
tfa.ammo.bo4ww.tundra=寒卷
tfa.ammo.bo4ww.scorp=高能电
tfa.ammo.bo4ww.impaler=铆箭
tfa.ammo.bo4ww.dg1=特斯拉弹头
tfa.ammo.bo4ww.alistairs=怪异糊糊