//RANDOM COD WONDER WEAPONS

tfa.keybind.miscww.jetgun.attack=吸
tfa.keybind.miscww.jetgun.attack2=恢复引擎

tfa.keybind.miscww.icelazer.attack=充能激光

tfa.keybind.miscww.sungod.altattack=充能烈日穿射

tfa.msg.miscww.sungod.hint=按下Alt-攻击/近战/按下缩放键来充能烈日穿射

tfa.ammo.miscww.hellfire=烈火细胞
tfa.ammo.miscww.crossbow=爆炸-焊接箭
