nzEffects = nzEffects or AddNZModule("Effects")

//game.AddParticles("particles/drops_powerups.pcf")
game.AddParticles("particles/drops_powerups_new.pcf")

game.AddParticles("particles/perks_cherry.pcf")
game.AddParticles("particles/perks_phd.pcf")
game.AddParticles("particles/perks_zombshell.pcf")
game.AddParticles("particles/perks_razor.pcf")
game.AddParticles("particles/perks_vulture.pcf")
game.AddParticles("particles/perks_winterswail.pcf")
game.AddParticles("particles/perks_chuggabud.pcf")

game.AddParticles("particles/perks_aat_blastfurnace.pcf")
game.AddParticles("particles/perks_aat_thunderwall.pcf")
game.AddParticles("particles/perks_aat_deadwire.pcf")
game.AddParticles("particles/perks_aat_fireworks.pcf")
game.AddParticles("particles/perks_aat_cryofreeze.pcf")
game.AddParticles("particles/perks_aat_turned.pcf")
game.AddParticles("particles/perks_aat_fallout.pcf")
game.AddParticles("particles/nz_pap_muzzleflash.pcf")

game.AddParticles("particles/magicbox.pcf")

PrecacheParticleSystem("nz_gum_machine_loop")

PrecacheParticleSystem("nz_powerup_classic_loop")
PrecacheParticleSystem("nz_powerup_classic_intro")
PrecacheParticleSystem("nz_powerup_classic_poof")
PrecacheParticleSystem("nz_powerup_flame_loop")
PrecacheParticleSystem("nz_powerup_flame_intro")
PrecacheParticleSystem("nz_powerup_flame_poof")
PrecacheParticleSystem("nz_powerup_elec_loop")
PrecacheParticleSystem("nz_powerup_elec_intro")
PrecacheParticleSystem("nz_powerup_elec_poof")
PrecacheParticleSystem("nz_powerup_simple_loop")
PrecacheParticleSystem("nz_powerup_simple_intro")
PrecacheParticleSystem("nz_powerup_simple_poof")
PrecacheParticleSystem("nz_powerup_glowy_loop")
PrecacheParticleSystem("nz_powerup_glowy_intro")
PrecacheParticleSystem("nz_powerup_glowy_poof")
PrecacheParticleSystem("nz_powerup_glowy_loop_alt")
PrecacheParticleSystem("nz_powerup_glowy_intro_alt")
PrecacheParticleSystem("nz_powerup_glowy_poof_alt")
PrecacheParticleSystem("nz_powerup_glowy_loop_alt_alt")
PrecacheParticleSystem("nz_powerup_glowy_intro_alt_alt")
PrecacheParticleSystem("nz_powerup_glowy_poof_alt_alt")

PrecacheParticleSystem("nz_pap_muzzleflash")
PrecacheParticleSystem("nz_pap_muzzleflash_3p")

PrecacheParticleSystem("nz_perks_cherry")
PrecacheParticleSystem("nz_perks_cherry_player")
PrecacheParticleSystem("nz_perks_phd")
PrecacheParticleSystem("nz_perks_zombshell")
PrecacheParticleSystem("nz_perks_razor_vm")
PrecacheParticleSystem("nz_perks_razor_trail")
PrecacheParticleSystem("nz_perks_vulture_stink")
PrecacheParticleSystem("nz_perks_winters")
PrecacheParticleSystem("nz_perks_winters_zomb")
PrecacheParticleSystem("nz_perks_chuggabud_tp")
PrecacheParticleSystem("nz_perks_chuggabud_ghost")

PrecacheParticleSystem("bo3_aat_blastfurnace")
PrecacheParticleSystem("bo3_aat_thunderwall")
PrecacheParticleSystem("bo3_aat_deadwire")
PrecacheParticleSystem("bo3_aat_deadwire_ground")
PrecacheParticleSystem("bo3_aat_deadwire_jump")
PrecacheParticleSystem("bo3_aat_fireworks")
PrecacheParticleSystem("bo3_aat_freeze")
PrecacheParticleSystem("bo3_aat_freeze_explode")
PrecacheParticleSystem("bo3_aat_turned")

PrecacheParticleSystem("bo3_aat_fallout_start")
PrecacheParticleSystem("bo3_aat_fallout_loop")
PrecacheParticleSystem("bo3_aat_fallout_zomb")
PrecacheParticleSystem("bo3_aat_fallout_zomb_floor")
PrecacheParticleSystem("bo3_aat_fallout_eyes")
PrecacheParticleSystem("bo3_aat_fallout_kill")

PrecacheParticleSystem("nz_magicbox")
PrecacheParticleSystem("nz_magicbox_sharing")