nzEffects = nzEffects or AddNZModule("Effects")

game.AddParticles("particles/drops_powerups.pcf")

game.AddParticles("particles/perks_cherry.pcf")
game.AddParticles("particles/perks_phd.pcf")
game.AddParticles("particles/perks_zombshell.pcf")
game.AddParticles("particles/perks_razor.pcf")
game.AddParticles("particles/perks_vulture.pcf")
game.AddParticles("particles/perks_winterswail.pcf")
game.AddParticles("particles/perks_chuggabud.pcf")

game.AddParticles("particles/perks_aat_blastfurnace.pcf")
game.AddParticles("particles/perks_aat_thunderwall.pcf")
game.AddParticles("particles/perks_aat_deadwire.pcf")
game.AddParticles("particles/perks_aat_fireworks.pcf")
game.AddParticles("particles/perks_aat_cryofreeze.pcf")
game.AddParticles("particles/perks_aat_turned.pcf")
game.AddParticles("particles/perks_aat_fallout.pcf")

game.AddParticles("particles/magicbox.pcf")

PrecacheParticleSystem("nz_powerup_purple")
PrecacheParticleSystem("nz_powerup_anti")
PrecacheParticleSystem("nz_powerup_global")
PrecacheParticleSystem("nz_powerup_global_intro")
PrecacheParticleSystem("nz_powerup_global_poof")
PrecacheParticleSystem("nz_powerup_local")
PrecacheParticleSystem("nz_powerup_local_intro")
PrecacheParticleSystem("nz_powerup_local_poof")
PrecacheParticleSystem("nz_powerup_mini")
PrecacheParticleSystem("nz_powerup_mini_poof")

PrecacheParticleSystem("nz_perks_cherry")
PrecacheParticleSystem("nz_perks_cherry_player")
PrecacheParticleSystem("nz_perks_phd")
PrecacheParticleSystem("nz_perks_zombshell")
PrecacheParticleSystem("nz_perks_razor_vm")
PrecacheParticleSystem("nz_perks_razor_trail")
PrecacheParticleSystem("nz_perks_vulture_stink")
PrecacheParticleSystem("nz_perks_winters")
PrecacheParticleSystem("nz_perks_winters_zomb")
PrecacheParticleSystem("nz_perks_chuggabud_tp")
PrecacheParticleSystem("nz_perks_chuggabud_ghost")

PrecacheParticleSystem("bo3_aat_blastfurnace")
PrecacheParticleSystem("bo3_aat_thunderwall")
PrecacheParticleSystem("bo3_aat_deadwire")
PrecacheParticleSystem("bo3_aat_deadwire_ground")
PrecacheParticleSystem("bo3_aat_deadwire_jump")
PrecacheParticleSystem("bo3_aat_fireworks")
PrecacheParticleSystem("bo3_aat_freeze")
PrecacheParticleSystem("bo3_aat_freeze_explode")
PrecacheParticleSystem("bo3_aat_turned")

PrecacheParticleSystem("bo3_aat_fallout_start")
PrecacheParticleSystem("bo3_aat_fallout_loop")
PrecacheParticleSystem("bo3_aat_fallout_zomb")
PrecacheParticleSystem("bo3_aat_fallout_zomb_floor")
PrecacheParticleSystem("bo3_aat_fallout_eyes")
PrecacheParticleSystem("bo3_aat_fallout_kill")

PrecacheParticleSystem("nz_magicbox")
PrecacheParticleSystem("nz_magicbox_sharing")