//BLACK OPS 4 WONDER WEAPONS

tfa.keybind.bo4ww.dg5.attack=震蕩
tfa.keybind.bo4ww.dg5.attack2=加電
tfa.keybind.bo4ww.dg5.altattack=放置

tfa.keybind.bo4ww.hellfire.attack=噴射火焰
tfa.keybind.bo4ww.hellfire.attack2=氣體沖擊
tfa.keybind.bo4ww.hellfire.altattack=地獄風暴

tfa.keybind.bo4ww.overkill.attack=開火
tfa.keybind.bo4ww.overkill.attack2=發射榴彈
tfa.keybind.bo4ww.overkill.altattack=自毀

tfa.keybind.bo4ww.katana.attack=劈砍
tfa.keybind.bo4ww.katana.attack2=殘暴突刺
tfa.keybind.bo4ww.katana.altattack=死亡暗影

tfa.ammo.bo4ww.winters=寒冰細胞
tfa.ammo.bo4ww.tundra=寒卷
tfa.ammo.bo4ww.scorp=高能電
tfa.ammo.bo4ww.impaler=鉚箭
tfa.ammo.bo4ww.dg1=特斯拉彈頭
tfa.ammo.bo4ww.alistairs=怪異糊糊