//BLACK OPS 4 WONDER WEAPONS

tfa.keybind.bo4ww.dg5.attack=Shock Slam
tfa.keybind.bo4ww.dg5.attack2=Electrocute
tfa.keybind.bo4ww.dg5.altattack=Power Plant

tfa.keybind.bo4ww.hellfire.attack=Flamethrower
tfa.keybind.bo4ww.hellfire.attack2=Blast Vent
tfa.keybind.bo4ww.hellfire.altattack=Infernal Tempest

tfa.keybind.bo4ww.overkill.attack=Onslaught
tfa.keybind.bo4ww.overkill.attack2=Grenade Launcher
tfa.keybind.bo4ww.overkill.altattack=Nuke

tfa.keybind.bo4ww.katana.attack=Kaze Slash
tfa.keybind.bo4ww.katana.attack2=Merciless Dash
tfa.keybind.bo4ww.katana.altattack=Shadow of Death

tfa.ammo.bo4ww.winters=Cold Cells
tfa.ammo.bo4ww.tundra=Frost Reels
tfa.ammo.bo4ww.scorp=Zip Zaps
tfa.ammo.bo4ww.impaler=Stake Bolts
tfa.ammo.bo4ww.dg1=Tesla Slug Rounds
tfa.ammo.bo4ww.alistairs=Goop
tfa.ammo.bo4ww.acid=Acid Flechette