//RANDOM COD WONDER WEAPONS

tfa.keybind.miscww.jetgun.attack=Shread
tfa.keybind.miscww.jetgun.attack2=Rev Engine

tfa.keybind.miscww.icelazer.attack=Charge Lazer

tfa.keybind.miscww.sungod.altattack=Charge Sun Shot

tfa.msg.miscww.sungod.hint=Press Alt-Attack/Bash/Suit-Zoom button to charge Sun Shot
tfa.msg.miscww.cng.hint=Press Alt-Attack/Bash/Suit-Zoom button to charge weapon
tfa.msg.miscww.cng.cancel=Press Reload button to cancel charge

tfa.ammo.miscww.hellfire=Fire Cells
tfa.ammo.miscww.crossbow=Explosive-Tipped Bolt
tfa.ammo.miscww.teslagat=Tesla Flechette
